### ISSUE TITLE
reduce item slots

### ISSUE THREAD

**Issue by MAXIS05** [ochotonida/artifacts#109]
I don't know if it can, but I was checking the curiosity settings, and it doesn't allow me to delete slots ...
It can?
if not, it would be good to have the option

**Comment by ochotonida** [comment]
Curios' server config allows you to add/remove slots, but it works a little bit different than most config files. You can find out how it works [here](https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users).

**Comment by MAXIS05** [comment]
It would be easy to remove the slots if they were added to the curios configuration file, but this is not the case, I don't know how the artifacts mod adds the slots, that is why I ask, how can I remove the slots?

**Comment by florensie** [comment]
I don't think it's possible to remove existing slots like that. Either way this feature would best be suggested to Curios rather than Artifacts.

Is there any reason you're trying to remove slots? There might be an alternative.

**Comment by ochotonida** [comment]
Slots added by mods aren't added to the config file, but you can still change them by adding them to the config file and setting `override = true`

**Comment by MAXIS05** [comment]
I would like to eliminate slots, because the interface is not comfortable for me, and I see it unnecessary to have two spaces for hands and two for jewels, it is precisely the slots that this mod adds that I want to remove, but if you cannot, there is no problem, that's why It was the suggestion to add the option to be able to configure that

**Comment by ochotonida** [comment]
Adding a config option for that in Artifacts doesn't make sense, since Curios already has a config for that.
Putting the following into your curios server config should set the amount of hand slots to 1. 
```
[[curiosSettings]]
  identifier = "hands"
  size = 1
  override = true
```
It's possible that you need to run `/curios reset <player>` for the changes to take effect, make sure to empty all your curio slots before running this command since it will reset them all.
Alternatively, you can also add slots using the curios command, although you have to do it for each player individually.

I'm not sure what you mean with jewel slots, the only slot Artifacts adds 2 of is hands, but you should be able to remove them the same way by changing the slot id.

If you still need help I'd suggest asking in Curios' discord instead.

**Comment by MAXIS05** [comment]
I'm going to try it, thanks
