### ISSUE TITLE
Artifacts fails to modifies loot tables in some cases

### ISSUE THREAD

**Issue by BarionLP** [ochotonida/artifacts#119]
A user of my mod Dungeons Enhanced has a issue with Artifacts and Dungeons Enhanced in combination.
Look at his report on my repository https://github.com/BarionLP/DungeonsEnhanced/issues/1
I can't find the problem in my code, maybe someone who knows about the artifacts code can also look into it.

**Comment by florensie** [comment]
Possibly related to #117

**Comment by florensie** [comment]
In fact, it appears you are overriding a whole bunch of vanilla loot tables, instead of injecting your changes to the existing ones. https://github.com/BarionLP/DungeonsEnhanced/tree/1.17.1/src/generated/resources/data/minecraft/loot_tables/chests

This will break the those loot tables for any other mods that add their own loot to vanilla chests, I hope you fix it.

**Comment by BarionLP** [comment]
I see what you mean but never changed the vanilla loot tables

**Comment by BarionLP** [comment]
Oh, this is caused by the forge data generators, I shouldn't call the super method...
