### ISSUE TITLE
Whoopee cushion does not have a slot.

### ISSUE THREAD

**Issue by RageQuitAmy** [ochotonida/artifacts#146]
In previous versions the whoopee cushion can be placed on the players head but in this version it can't be placed on the head. It doesn't even say it has a slot. I looked at changelogs and configs and don't see anything about it being changed. 

Nothing to reproduce exactly. xD Like I said it just doesn't have a slot. 

Versions:
 - Artifacts: artifacts-1.18.2-4.0.7
 - Forge: 1.18.2 40.1.0

The curios mod does look a bit buggy so I don't know if that is messing with anything.
![image_2022-04-30_231727159](https://user-images.githubusercontent.com/73620990/166124416-2f937912-aa39-408f-8e91-4bf5ad3e2b5b.png)

I am sorry if this was intended or if I just missed something. Any help would be appreciated.

**Comment by ochotonida** [comment]
Thanks for the report. 
The whoopee cushion is supposed to have the 'Curio' slot type, which allows it to be equipped in any slot. What likely happened here is that another mod (or the modpack, if you didn't make it yourself) accidentally removed it, either by replacing the item tag or because their item tag json is invalid. 
Unfortunately there isn't really anything I can do to fix this from my end. To figure out which mod is causing this you can try removing mods until the whoopee cushion gets it's slot type back. A good place to start is to type `$curio` in JEI, this should give you all items that have the 'Curio' slot type. If any items show up, it's probably the mod that adds those.

The pink and black squares are just a missing texture, nothing to worry about. If it's bothering you you can report, it if you know which mod adds the hair slot.

**Comment by RageQuitAmy** [comment]
That fixed it. Thank you so much! Also learned something about curio slot types. :D
