### ISSUE TITLE
Please make effects permanent

### ISSUE THREAD

**Issue by TheButterbrotMan** [ochotonida/artifacts#150]
To see reason why, please checkout this issue: https://github.com/TheButterbrotMan/Deathdusk/issues/78

**Comment by Aizistral** [comment]
You literally suggest to change how the mod works solely because some other mod/datapack/whatever-is-it-in-your-modpack supplements application of status effects with noise. This is not an expected behavior and would cause similar issue with a lot of other mods that grant countinuously refreshed status effects, one way or another. Artifacts is not responsible for this and has no obligation to fix this.

P.S. Just my opinion. Maybe @ochotonida has something different to say about it, I just couldn't help but get irritated at this demonstration of incompetence.

**Comment by florensie** [comment]
There is no such thing as a permanent status effect.

**Comment by Aizistral** [comment]
> There is no such thing as a permanent status effect.

Yes also this.

**Comment by TheButterbrotMan** [comment]
> There is no such thing as a permanent status effect.

If you cant help, you should just: shut the fuck up. 

I dont know, why are you getting that rude. Maybe just an asshole.

**Comment by TheButterbrotMan** [comment]
> You literally suggest to change how the mod works solely because some other mod/datapack/whatever-is-it-in-your-modpack supplements application of status effects with noise. This is not an expected behavior and would cause similar issue with a lot of other mods that grant countinuously refreshed status effects, one way or another. Artifacts is not responsible for this and has no obligation to fix this.
> 
> P.S. Just my opinion. Maybe @ochotonida has something different to say about it, I just couldn't help but get irritated at this demonstration of incompetence.

If you cant help, you should just: shut the fuck up.

I dont know, why are you getting that rude. Maybe just an asshole.

**Comment by TheButterbrotMan** [comment]
> I dont know, why are you getting that rude. Maybe just an asshole.

Ok, thougth there is. Thank you! :)

**Comment by TheButterbrotMan** [comment]
> There is no such thing as a permanent status effect.

Ok, thougth there is. Thank you! :)

**Comment by ochotonida** [comment]
I don't think there's much that can be done on my end to fix this. Even if there was, that wouldn't fully resolve the issue, as plenty of other mods add effects in a similar manner (including vanilla's Turtle Shell). 
It's probably a good idea to contact the developer of the mod that adds the sound effect, and suggest the sound only plays when an effect is applied that the player doesn't already have.

**Comment by TheButterbrotMan** [comment]
> There is no such thing as a permanent status effect.

There is!
Just figured it out. Here is a example:
`StatusEffectInstance p = new StatusEffectInstance(
  effect,
  Integer.MAX_VALUE,
  amplifier,
  false,
  false
);
p.setPermanent(true);`

**Comment by ochotonida** [comment]
That doesn't fully solve the issue though. When unequipping the item, the effect would need to be cancelled instead of letting the effect run out, but that could also remove an effect of the same type and level the player already had before equipping the item. Vanilla doesn't use this for the Turtle Shell for the same reason.
