### ISSUE TITLE
[Enhancement] Add more everlasting foods

### ISSUE THREAD

**Issue by GreatestFool** [ochotonida/artifacts#16]
Specifically, I'm talking about an everlasting carrot, baked potato and mushroom so that all the ingredients for the everlasting rabbit stew are everlasting.

I've actually tried to replicate the way you made your everlasting items with both ContentTweaker and by making my own mod, and while I managed to make them everlasting, I kept having the issue that the hunger values didn't get applied to the player. At this point I've just given up because I don't have enough time to bugfix anymore, but I was hoping that you could add them? It isn't anything critically important, I just think it'd be nice for the recipe to be made out of other everlasting items.

Sorry for taking up your time if this isn't something you want to do.

**Comment by GreatestFool** [comment]
Is there a reason you closed this?

**Comment by ochotonida** [comment]
I've decided to no longer update the 1.12 version of this mod. The 1.15 version only has one everlasting food item (beef/steak), and I don't really plan on adding other variants

**Comment by GreatestFool** [comment]
That's understandable. Would you be open to adding crafttweaker support once that enters stable on 1.15?

**Comment by ochotonida** [comment]
That's something I'd have to look into, since I've never really done anything with crafttweaker before, but I'm not sure if it would be worth the effort. Either way, it should be relatively straightforward to create a mod yourself that adds all the other variants, the way  food works in 1.15 is a lot more flexible than it was in 1.12. If this is something you'd like some help with don't hesitate to ask.

**Comment by GreatestFool** [comment]
Thanks for the offer, I really appreciate it! I'm pretty busy at the moment, so I might not have time until a good few months down the road if that's fine?
