### ISSUE TITLE
Boots bug or something

### ISSUE THREAD

**Issue by angefco** [ochotonida/artifacts#176]
All of Fabric 5  - Server

I cant jump under water and my jump pass from 1 block to a half block, id
![Uploading 2022-09-23_05.49.08.png…]()
k whats the problem, i just got this boots and dont tell something about that

**Comment by angefco** [comment]
![2022-09-23_05 49 08](https://user-images.githubusercontent.com/114135776/191946771-95db53c0-c0d5-4f36-841c-bf592c026093.png)

**Comment by ochotonida** [comment]
I can't reproduce this issue, although from your description it's not really clear what the issue is or how to reproduce it.

Either way, this is the issue tracker for the Forge version of Artifacts. Issues with the Fabric version of Artifacts should go on the issue tracker for the Fabric version. If you're still having this issue, you can open a new issue here: https://github.com/florensie/artifacts-fabric/issues.

Please remember to fill in the issue template rather than just deleting it entirely.
