### ISSUE TITLE
 Can't use the mod inside a server

### ISSUE THREAD

**Issue by zpauk** [ochotonida/artifacts#186]
Hi, I am using the Artifacts mod inside a server powered by Mohist software, but for some reason when I log out of the server and back in, I can't use the mod anymore, it won't let me open the menu or see the artifacts on my , the menu does not open with the configured key either

**Comment by ochotonida** [comment]
This is a compatibility issue between Curios and Mohist/specific Mohist plugins. There might be a specific plugin that is causing this, you could try disabling some until you find the one that is causing the issue. Mohist is not officially supported by Curios, since it often causes issues with mods.
