### ISSUE TITLE
[Suggestion] Make the timers for the effects "better"

### ISSUE THREAD

**Issue by INooBTooMuch** [ochotonida/artifacts#189]
The timers for effects like night vision or jump bust could be changed to the xx:xx instead of the refreshing timers and this way when an artifact is unequipped the effect would immediately stop instead of remaining for the rest of its timer.

Minecraft : 1.18.2
Forge : 40.2.0
Artifacts : 4.2.0

**Comment by ochotonida** [comment]
The way effects are displayed is actually completely unrelated to when the effect ends, but I've updated these items to immediately remove their effect after unequipping in version 1.19.3-6.0.0. Unfortunately this won't be backported to 1.18, since I don't have the time to maintain Artifacts for multiple Minecraft versions at once.
