### ISSUE TITLE
Mimics not compatible with industrial foregoing mob capture tools

### ISSUE THREAD

**Issue by Brown-bricks** [ochotonida/artifacts#190]
**Describe the bug**
Neither right-clicking mimics with the capture tool or using the infinity launcher seems to work.

**To Reproduce**
1. Spawn or encounter a mimic
2. Attempt to use a mob capture tool (from Industrial foregoing) on the mimic

**Game Environment**
Custom modpack. 
 - Artifacts: 1.19.2-5.0.1
 - Forge: 43.2.3
 - Industrial Foregoing 1.19.2-3.3.2.2-4

**Comment by ochotonida** [comment]
This was actually intentional behavior, to prevent them from being duplicated using the mob duplicator. In version 1.19.3-6.0.0 I've replaced removed the industrialforegoing:mob_imprisonment_tool_blacklist tag from mimics and replaced it with the industrialforegoing:mob_duplicator_blacklist tag, so you'll be able to capture mimics in mob capture tools but still not duplicate them.
