### ISSUE TITLE
Implement durability

### ISSUE THREAD

**Issue by Pendrag00n** [ochotonida/artifacts#214]
The fact that artifacts don't get damaged over time seems to overpowered. Would be great to have an option to toggle durability in the config

**Comment by Pendrag00n** [comment]
#82 Implies that this feature already exists, but I can't find it inside the config files. (v6.0.4 on 1.19.3)

common.json5
![image](https://github.com/ochotonida/artifacts/assets/88731722/698849f7-5529-4e5f-a0ca-c3ea790709ba)

client.json5
![image](https://github.com/ochotonida/artifacts/assets/88731722/f723a5b0-3e25-46a1-b371-c9d28aef555b)

_serverconfigs_ folder doesn't seem to include any file related to artifacts
![image](https://github.com/ochotonida/artifacts/assets/88731722/c73207ad-d6b6-4796-95b6-7b9a3672cfe3)

**Comment by ochotonida** [comment]
There used to be a durability config option for each artifact, but it was removed since it was too much work to maintain.
Since there were no default values and you had to set the value individually for each artifact, the feature that wasn't really used all that much, so it wasn't really worth keeping.

There are gamerules that you can use to make artifacts more or less powerful, but a config option for durability is unfortunately not something I plan on adding back.
