### ISSUE TITLE
Can't change everlasting beef cooldown timer in 9.1.0

### ISSUE THREAD

**Issue by NolanHewitt** [ochotonida/artifacts#225]
The new version seemed to have removed the rule that allowed us to change the cooldown on the everlasting beef. Can this be brought back?

**Comment by ochotonida** [comment]
Does `/gamerule artifacts.eternalSteak.cooldown <time>` no longer work for you? It wasn't removed and it's still working as intended on my end, so I'm not sure what the issue is.

**Comment by NolanHewitt** [comment]
In the previous version I could add "everlastingFoodCooldown = 10000" in the general.toml file, or just by modifying it in the config in mod menu, changing it for all worlds. Changing it using the game rule would have to be done on every world, and would require temporarily enabling cheats on already created worlds to change the game rules.

**Comment by NolanHewitt** [comment]
I've found a mod which solves this issue for me: https://modrinth.com/mod/boring-default-game-rules

**Comment by ochotonida** [comment]
All of the item-specific config options were replaced with game rules when Artifacts was ported to 1.19.3, when switching from Forge's config API to Cloth Config. Most of the item-specific config options weren't available in the Fabric version before then. While I could have used cloth config for these config options as well, game rules are a lot easier to maintain, and they also make it easier for users to test out different values while playing.
Not being able to change the default value for all worlds is something I considered, but since there are mods that add default game rules for both Fabric and Forge, I don't think this is a major issue.
