### ISSUE TITLE
Error Artifacts on 1.20.1, crash at initializing

### ISSUE THREAD

**Issue by jorlopgil** [ochotonida/artifacts#226]
Any idea? 

https://pastebin.com/VdFyvdnp

**Comment by ochotonida** [comment]
Does this also happen when you don't have Artifacts installed? Iris (or Oculus) seems to be what's crashing here, there's no mention of Artifacts in your crash report.

(In the future, please don't paste the entire crash log in your issue description, it makes it a bit harder to read and clutters up the discussion. You can just drag the file into the issue when creating it, or alternatively use a site like pastebin)

**Comment by jorlopgil** [comment]
> Does this also happen when you don't have Artifacts installed? Iris (or Oculus) seems to be what's crashing here, there's no mention of Artifacts in your crash report.
> 
> (In the future, please don't paste the entire crash log in your issue description, it makes it a bit harder to read and clutters up the discussion. You can just drag the file into the issue when creating it, or alternatively use a site like pastebin)

Without the artifacts it works without problems, with more than 40 mods. I have tried updating Forge to the latest version and nothing.

**Comment by ochotonida** [comment]
Looking at Oculus' issue tracker, it seems like this crash happens when Forge's mod loading fails for any reason. Not sure why Oculus doens't just let Forge do it's thing.
You'll have to look at your latest.log to find what the actual problem is, but you're probably just missing one of Artifacts' dependencies. Make sure you have Architectury, Curios and Cloth Config installed.
