### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by bloodyraoul** [ochotonida/artifacts#227]
Add durability to artifact to they are not eternal
Add config for each so the strongest ones can be configured to have low durability

This feature was there before ? no ?

**Comment by ochotonida** [comment]
There used to be a durability config option for each artifact, but it was removed since it was too much work to maintain and somewhat buggy. Since there were no default values and you had to set the value individually for each artifact, the feature that wasn't really used all that much, so it wasn't really worth keeping.

There are game rules that you can use to make artifacts more or less powerful, but a config option for durability is not something I plan on adding back.

**Comment by bloodyraoul** [comment]
ho, too bad for me, it was really something I wanted
If you want to only add a global durability, all the same for all artifacts, i'm ok also :)

**Comment by florensie** [comment]
A global durability setting wouldn't help much (if at all) with the complexity. The complexity comes from figuring out how to decrease the durability of each item.

**Comment by Pendrag00n** [comment]
Not having a durability option in the config makes this mod literally unplayable and too overpowered on servers
