### ISSUE TITLE
Something with Nightvision?

### ISSUE THREAD

**Issue by Darakudemion** [ochotonida/artifacts#235]
https://mclo.gs/b6bOyDy

**Comment by ochotonida** [comment]
Please fill in the issue template next time.

From your log it looks like Artifacts is crashing because multiple mods are failing to load before that, but the actual issue doesn't seem to be caused by Artifacts. I can't tell for sure since there's multiple mods having issues in your log, but from first glance it looks like it's caused by create or one of its addons.
