### ISSUE TITLE
Feral Claws {DISABLE} ??

### ISSUE THREAD

**Issue by kamiidagamer** [ochotonida/artifacts#239]
**Describe the bug**
When finding the feral claws within a chest. One sees the green claws and description clearly. However, the item does not show in the craft menu. Plus, once taken out of the chest and placed into inventory. The item will disappear, then stating in grey lettering "something item is Disable" 

**To Reproduce**
Steps to reproduce the behavior:e
1. Go to 'a chest containing item "feral claws"'
2. Click on 'the claws, then drag them into your inventory'
3. See error

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: [v9.2.0]
 - Forge/Fabric Api: [fabric- 0.14.25]
 - [other relevant mods...] this is happing in Prominence 2 mod pack

**Comment by ochotonida** [comment]
I believe this is something Prominence 2 is doing to disable the item, likely for balancing purposes, I've had a similar report in the past. They're using a script of some sort to delete the item once it enters your inventory. Since this is not added by Artifacts, I unfortunately can't help you re-enable the item.

Artifacts adds game rules which can be used to tweak or disable Artifacts, but the developers of the modpack you're using are likely unaware of this. You might want to suggest to them to use these game rules instead, since this would allow players to re-enable the artifacts they've disabled, without having to find and edit the script that's doing it.
