### ISSUE TITLE
Compatibility issue between VanillaTweaks and Artifacts

### ISSUE THREAD

**Issue by leiseg** [ochotonida/artifacts#285]
**Describe the bug**
When wearing a chest plate enchanted with Vigor I or III (enchantment from VanillaTweaks which adds one heart per enchantment level) and the Crystal Heart artifact from Artifacts, the last heart won't regenerate past 50%. Wearing a chest plate with Vigor II doesn't cause that issue. I will report this issue to the creator of VanillaTweaks too.

**To Reproduce**
1. Join a world with only Artifacts and VanillaTweaks (and their dependencies) installed
2. Give yourself a Vigor I or III chest plate and the Crystal Heart artifact
3. Equip both items and let your health regenerate
4. See last heart being stuck at 50%

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 9.5.9
 - Fabric Api: 0.92.2+1.20.1
 - VanillaTweaks: 1.5.71

**Comment by ochotonida** [comment]
From what I can tell, this isn't actually a bug. The Crystal Heart increases your max health by 5 hearts, whereas vigor increases your health by 10% per level. If you have both vigor and a Crystal Heart, your total health is `(20 + 10) + (20 + 10) * (level/10)`, which is 16.5 hearts for Vigor I and 19.5 hearts for Vigor III. Since Minecraft displays health in full hearts, it looks like there's half a heart that won't regenerate.
