### ISSUE TITLE
Crash during Startup w/ 'Combatify' (formerly 'Atlas Combat') MCv1.19.2

### ISSUE THREAD

**Issue by Happenstance-14** [ochotonida/artifacts#286]
Game crashes during early startup phase.  Report blames 'BootstrapMethodError' 'RuntimeException', something about mixins.  See crash report w/ Quilt 0.26.0 attached below; _identical crash occurs w/ latest Fabric version for 1.19.2_.

[crash-2024-06-07_21.48.17.5556-quilt_loader.txt](https://github.com/user-attachments/files/15746503/crash-2024-06-07_21.48.17.5556-quilt_loader.txt)

This may well be an issue w/ Combatify, but unfortunately its development is discontinued for MCv1.19.X.

Environs:—
- **MC 1.19.2**
- **Quilt 0.26.0**
- QFAPI 4.0.0-beta.30
- QSL 3.0.0-beta.29
- FAPI 0.76.0
 - **'Artifacts' 7.1.1+fabric**
 - 'Cloth Config API' 8.3.115
 - 'Architectury API' 6.6.92-fabric
 - 'Trinkets' 3.4.2 (or Polymer port)
 - **'Atlas Combat' (Combatify)1.1.7**
 - 'owo-lib' 0.9.3

**Comment by ochotonida** [comment]
Unfortunately the Fabric version Artifacts is no longer being actively maintained for 1.19.2. I didn't originally develop the earlier Fabric versions of Artifacts, and only took over after 1.19.4 released.
That being said, since this is a mixin conflict, properly fixing this issue would likely require an update from both mods anyways, so unless Combatify would also get an update, it's not really worth fixing this on my end.
