### ISSUE TITLE
Item Generation (Feral Claws and others) disappear from inventory after looting

### ISSUE THREAD

**Issue by gonchox** [ochotonida/artifacts#299]
**Describe the bug**
Whenever Feral Claws and also other artifacts are looted, they dissapear from inventory and a message points out saying "this item is deactivated"

**To Reproduce**
1. Go to 'Any world with Prominence modpack installed'
2. Spawn or loot' Feral claws artifact'
3. See error

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 9.5.5
 - Forge/Fabric Api: 0.15.11
 - [other relevant mods...]: Prominence II RPG

**Comment by ochotonida** [comment]
These items have been disabled by Prominence II, you'll have to ask them how to re-enable them since this is not a feature added by Artifacts. I'm not sure why they haven't removed the items from the loot tables, or nerfed them using Artifacts' game rules instead, since this would probably less confusing to users.
