### ISSUE TITLE
Split up the head.json into a hat.json and a face.json

### ISSUE THREAD

**Issue by GoldenFurredFox** [ochotonida/artifacts#306]
The Snorkel (`artifacts:snorkel`) and Night Vision Goggles (`artifacts:night_vision_goggles`) don't really belong on your head.

They're both considered to be worn on your face in real life since the goggles only really augment your eyes and the snorkel augments both your eyes and mouth.

As such, my proposal is to split up the `head.json` file into a `hat.json` file and a `face.json` file.

The `face.json` file could then contain just those two entries, while the `hat.json` file could contain everything the `head.json` file currently contains minus what got moved to the `face.json` file.

(Apologies for the numerous edits; I had assumed I knew what changes were necessary and proposed precise file changes that ultimately proved not to be functional.)

**Comment by ochotonida** [comment]
The main reason I haven't done this yet is because I don't think just 2 items warrants adding a whole extra slot. Having a limited number of slots keeps things interesting and (somewhat) balanced, since you can't just equip every artifact you find. Perhaps in the future, although I'll have to add some more face slot artifacts first.
