### ISSUE TITLE
Boot Slot missing Icon

### ISSUE THREAD

**Issue by slave2midna** [ochotonida/artifacts#49]
#### Versions (Be specific, do not write "latest"):
* Curios: 4.0.3.3
* Forge/Fabric: 35.1.4
#### Steps to Reproduce:
1. Install Curios API with extra mod 'Artifacts'
2. Open Curios inventory and notice the addition of a 'boots' slot, with not icon to show for it.

Not sure if this is a bug, or intended - I personally don't see the need for a 'boot' slot as you already have one for armor. But it appears that this mod adds the slot as a blank square for the boots but no actual icon for it. I'm not sure if this is a bug on the mod side, or the Curious side, so I figured I'd post here. Personally still feel that Curios doesn't need a 'boot' slot for its items and this should be an optional slot that can be removed or disabled.

**Comment by ochotonida** [comment]
I can't reproduce the issue, even with the versions you specified. I'm assuming by 'boots' you mean feet, as this mod does not add a boots slot. The feet slot added by this mod uses the vanilla armor slot icon.
The reason why I'm using a separate slot is because the items from this mod that go in that slot have a different function than armor, and I don't want them to be mutually exclusive with armor.

**Comment by slave2midna** [comment]
Oh! Thank you! That got me on the right direction, turns out - it's something of an issue with the resource pack I'm using. I think I can fix it, just need to name an image in the pack I believe. Thank you for the help! I understand not wanting them to be exclusive! No worries!
