### ISSUE TITLE
[Suggestion] Allow hats to also be placed in the head equipment slot

### ISSUE THREAD

**Issue by ChloeDawn** [ochotonida/artifacts#60]
Sometimes I just want to look cool (especially useful with the Cosmetic Armor mod)

**Comment by ochotonida** [comment]
The reason I don't really want to do this is that you would essentially gain two extra slots for artifacts (since I'd have to do the same for the feet slot as well). Curios does have cosmetic slots though, [you can enable them in the server config](https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users).
