### ISSUE TITLE
Enemies can see the Scarf of Invisibility

### ISSUE THREAD

**Issue by NielsPilgaard** [ochotonida/artifacts#62]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/1322

There is a bug with the Scarf of invisibility at the moment where even if you have no armor on you and nothing in your hand mobs can still see you no problem.

### Versions
- Artifacts-1.16.5-2.7.7
- Forge-1.16.5-36.0.22

**Comment by ochotonida** [comment]
I can't seem to reproduce this, even on E6. If this is an issue it probably isn't caused by Artifacts, the only thing the scarf does is applying the vanilla invisibility effect to the player. Whether the model is visible or not doesn't have an effect, because this information is only available on the client.

Even with no armor, you can still get detected though (at a range of a little over 1 block for most mobs), after which they will track you as normal.

**Comment by NielsPilgaard** [comment]
I just tried and can't reproduce it either, apologies for relaying without verifying first :)

**Comment by ochotonida** [comment]
No problem!
