### ISSUE TITLE
Can I Make New Artifacts?

### ISSUE THREAD

**Issue by Vanthanyx** [ochotonida/artifacts#95]
Is there a way for me to code more artifacts without entirely copying your base code, like the Origins Mod. Can you make it so you can make it a dependancy then just code a new artifact and give it a skin, powers, and loot tables?

**Comment by ochotonida** [comment]
No, this is currently not possible without copying some code, although in the end, most artifacts are just pretty basic implementations of curios. Creating some sort of api would require more work and maintenance than it's worth, and I doubt many people are going to make addons rather than just standalone mods.
