### ISSUE TITLE
Helium Flamingo issues (probably) caused by better diving.

### ISSUE THREAD

**Issue by Darkmega18** [ochotonida/artifacts#98]
**Describe the bug**
Helium flamingo seems to be permanent until touching ground or removed, also can't disable until touching ground unless removed.

**To Reproduce**
Put the mods together. (artifacts and better diving)

Go swim in the air with flamingo. > you can go constantly until you touch ground and will hover in midair due to better diving's mechanics I'd guess.

As a side it says it should be temporary? But doesn't say how temporary. But I'd guess it's related to breathe meter above water or swimming mechanics... which are changed also by better diving. Such as not sinking gradually and always having directional movement.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: Artifacts-1.16.5-2.9.3
 - Forge: 36.1.24
 - Better Diving: BetterDiving-1.16.5-1.2.5.jar
 
 Lots of other mods, but this is the only issue found so far.

**Comment by ochotonida** [comment]
The usual behavior of the helium flamingo is indeed related to the breath meter, the effect should be cancelled after a small amount of time, when the breath meter runs out.
The problem here is that Better Diving makes some pretty significant changes to the vanilla breath meter behavior using ASM, which in many cases doesn't play nice with other mods. I'd be more inclined to try to find a way to fix this if Better Diving used mixins instead, which are actually designed to be non-instrusive.

I've also noticed that some of the swimming mechanics like swimming up/down using space/shift don't properly work above water when using Better Diving, although that's not this mod's responsibility to fix (see linked issue)

**Comment by Darkmega18** [comment]
alrighty, would it be prudent to put this request towards better diving in hopes of a change or some cross mod help with the issue and this and probably other mods?

**Comment by ochotonida** [comment]
To be honest, I'm not sure whether complete compatibility is even possible with my current implementation. Better Diving changes the duration you can stay underwater and the way the breath meter is rendered, both of these things would probably cause additional issues on my end. Replacing my current implementation with one that doesn't use the breath meter at all would fix these issues, but I'm a bit short on time right now so it'll have to wait a bit.

I'm not sure whether the issues with the swimming mechanics have a simple fix, but I'll leave that up to @florensie to solve.

**Comment by Darkmega18** [comment]
thats fine. I did remove better diving from my pack currently cause of a couple of issues related to swimming, breathe or both that occur in other collectibles and power ups (which would also get nullified or become less useful if it exists currently, like origins merling start, diving gear, enigmatic legacy's will of the ocean and such). but it is a mod I am rather fond off. so on your suggestion having it be made better to play nicer could be great.

**Comment by ochotonida** [comment]
I've updated the mod to no longer use player's air supply, which should solve most of these issues.

**Comment by Darkmega18** [comment]
so it uses it's own meter that appears somewhere? :o
