### ISSUE TITLE
Weird Side Effects from Shaders

### ISSUE THREAD

**Issue by githubbingitup** [ochotonida/artifacts#99]
when using latest version with Iris - most shaderpacks make some of the items in this pack look very strange. I think its due to the way they might be lit. 

Such as the night vision gauntlets and fire gauntlet, they become ultra bright blocks with most shaders.

**Comment by ochotonida** [comment]
Iris is a Fabric mod, please report this to the issue tracker of the Fabric version of this mod (https://github.com/florensie/artifacts-fabric/issues).
That being said, the models of the artifacts you mentioned do emit light, so this might be an issue with the shaders themselves rather than the Artifacts. (a screenshot might help :))

**Comment by florensie** [comment]
Better yet: open an issue on Iris' issue tracker instead and include screenshots. Iris is an early beta and has many issues, make sure to check if the issue isn't listed already.
